### PR TITLE
Dev main

### PR DESCRIPTION
**Pull request by nbhoski**
This PR contains the fix for #320 
* Verify Any backward compatibility

### CODE REVIEW

**Comment by sameagen-MW** [comment]
Don't merge until issue #339 is fixed, as I think that potentially represents a breaking change.

**Comment by sameagen-MW** [comment]
Issue #339 has been closed.

**Comment by Vahila** [comment]
Qualifications made are documented [here](https://mathworks.atlassian.net/wiki/spaces/CI/pages/214842886/Jenkins+Bash).

**Review by Vahila — APPROVED** [review]
LGTM!

Qualification checks made in Windows, Linux and Mac can be found [here](https://mathworks.atlassian.net/wiki/spaces/CI/pages/214842886/Jenkins+Bash).

**Pull request merged**
