### PR TITLE
matlab-2.1.4-Qualification

### PR DESCRIPTION
**Pull request by nbhoski**
This qual branch includes fix for .

#128 #129  #132 #134 #138 

##Features 
* Using genscript package instead of runMatlabTests.m #130

### CODE REVIEW

**Review by SangaviJayagopi — COMMENTED** [review]
Open issues: #151 and #152

**Review by SangaviJayagopi — APPROVED** [review]
#151 and #154 closed

**Comment by nbhoski** [comment]
@SangaviJayagopi  should #152 be closed ?

**Comment by abhargav-mw** [comment]
#152 is closed after qualification. Merging this PR

**Pull request merged**
