### PR TITLE
3.0.0 qualification

### PR DESCRIPTION
**Pull request by abhargav-mw**
### Added new features:

- Test filter support in Pipeline projects
- Test filter support in Freestyle projects
- MATLAB tool installation support in Freestyle (and Multi-configuration projects)

### CODE REVIEW

**Comment by abhargav-mw** [comment]
#177 Opened a bug for missing help text for MATLAB

**Comment by nbhoski** [comment]
@mw-hrastega  please verify the help text added for https://github.com/mathworks/jenkins-matlab-plugin/pull/176/commits/f64aaceb4e39eb268bcbe97f02c2c727bca33f8e  and let me know if any changes required.

**Comment by mcafaro** [comment]
There's a large gap between "By folder name" and "By tag" when I use this version of the plugin:

Screen Shot 2021-01-25 at 4 43 42 PM

**Comment by mcafaro** [comment]
Also the "File path:"/"Tag name:" under each option feels a bit out of place on its own line. Do we need these? If so, can they go to the left of the text field instead?

Screen Shot 2021-01-25 at 4 47 08 PM

**Review by SangaviJayagopi — APPROVED** [review]
Qual checks made in Mac OS:

1. Testing done for pipeline, free-style, multi-config projects for Test folder and tag filter support
2. Testing for Global tools in free-style and multi-config
3. Qualified older project builds in Jenkins with the new plugin, build configuration date remained same and ran successfully
4. Passed few regression tests

**Comment by nbhoski** [comment]
> There's a large gap between "By folder name" and "By tag" when I use this version of the plugin:
> 
> Screen Shot 2021-01-25 at 4 43 42 PM

I guess the gap is very browser-specific and default if you look at the screenshots of what@houman has updated there its looks perfectly fine.

**Comment by abhargav-mw** [comment]
### Release Version 
The release version for changes in this PR will be **2.4.0** considering no backwards incompatibility.

**Review by Vahila — APPROVED** [review]
Qualification checks made in Windows and Linux:

- Testing 'Test folder selection' by Folder and Tags for Pipeline, Free Style and Multi Config projects
- Testing Global tool in Free Style, Multi Config and Pipeline projects
- Checked for Backwards Compatibility with previous versions

**Review by RekhavathiG — APPROVED** [review]
Qualified the features. Looks good.

**Pull request merged**
